### ISSUE TITLE
Ahh Juicy One 

### ISSUE THREAD

**Issue by AlishahMughal123** [mdn/beginner-html-site#11]
Thanks for sharing :) .

Umm want to ask about , is there any open source related to html & css (Web Dev) ? if you know kindly drop the links , & do you also do open source any?

**Comment by aamangupta** [comment]
you can see courses on coursera or can visit youtube channels like Traversy Media, programming with harry, freecodecamp ,code withmosh etc.

**Comment by AlishahMughal123** [comment]
Oh okay cool Thanks man :)

**Comment by codigo1945** [comment]
hola a todos
me siento como un hacker mandando mensajes por aqui ya que solo sabia escribir por ws o facebook
soy nuevo en la programacion estoy estudiando con cursos de youtube,
pero no se si voy por buen camino ps son cursos que es para hacer paginas
y a mi lo que me interesa es el codigo
no se si es la manera correcta de aprender.
gracias

**Comment by schalkneethling** [comment]
Please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.
