### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by JosephBridge** [mdn/beginner-html-site#45]
https://github.com/mdn/beginner-html-site/blob/81583405a9374758d78912dd1e06995340060608/index.html#L13C1-L13C5

**Comment by schalkneethling** [comment]
> https://github.com/mdn/beginner-html-site/blob/81583405a9374758d78912dd1e06995340060608/index.html#L13C1-L13C5

Hey @JosephBridge - Did you have a specific question about the lines you referenced?
